name: gr0ve
description: "For BCA"
publish_to: "none"

version: 2.2.0+37

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  http: ^1.6.0
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.0
  shared_preferences: ^2.5.4
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  icons_plus: ^5.0.0
  table_calendar: ^3.2.0
  flutter_local_notifications: ^20.0.0
  firebase_messaging: ^16.1.1
  hugeicons: ^1.1.5
  firebase_analytics: ^12.1.2
  csv: ^7.1.0
  html: ^0.15.6
  flutter_html: ^3.0.0
  flutter_markdown: ^0.7.7+1
  flutter_dynamic_launcher_icon: ^0.0.2
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  just_audio: ^0.10.5
  crypto: ^3.0.6
  path_provider: ^2.1.5
  audio_session: ^0.2.2
  image_picker: ^1.1.0
  firebase_storage: ^13.1.0
  googleapis: ^16.0.0
  googleapis_auth: ^1.6.0
  flutter_dynamic_icon_plus: ^1.4.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/credentials/gsheets.json
    - assets/credentials/service_account.json
    - assets/profile/academy/
    - assets/app_icons/png/
    - assets/profile/grover/
    - assets/profile/aspen/
    - assets/profile/rowan/
    - assets/profile/sakura/
    - assets/profile/abies/
    - assets/profile/cedite/
    - assets/story/characters/
    - assets/story/characters/ep0/
    - assets/story/characters/ep1/
    - assets/story/characters/ep2/
    - assets/story/characters/ep2/sheep/
    - assets/story/characters/ep2/baby/
    - assets/story/characters/ep3/
    - assets/story/inventory/
    - shorebird.yaml
    - .env
