// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDeU8w4ytIE41g1Wr810ubGr5rC9zlWk',
    appId: '1:354104126282:web:d1a68662557f6df63d2fb3',
    messagingSenderId: '354104126282',
    projectId: 'gr0ve-bca',
    authDomain: 'gr0ve-bca.firebaseapp.com',
    storageBucket: 'gr0ve-bca.firebasestorage.app',
    measurementId: 'G-DPXHERQ7NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARGtMmvcPokMxr12UpL9WCD_S7aT3Swno',
    appId: '1:354104126282:android:15f9f15cc0b25e0c3d2fb3',
    messagingSenderId: '354104126282',
    projectId: 'gr0ve-bca',
    storageBucket: 'gr0ve-bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUTdIriu95POX2wlrOPuZPksJFEE9HbU4',
    appId: '1:354104126282:ios:d649644b81b548dd3d2fb3',
    messagingSenderId: '354104126282',
    projectId: 'gr0ve-bca',
    storageBucket: 'gr0ve-bca.firebasestorage.app',
    iosBundleId: 'com.arjunyuvaraj.gr0ve',
  );

}